export const leasesCatalog = [
  {
    property_slug: 'aci-paragon-plaza-3310',
    tenant_name: 'Paragon Plaza Unit 3310',
    lease_number: 'LSE-PARAGON-3310',
    start_date: '2025-01-01',
    end_date: '2026-12-31',
    rent_amount: 35000,
    security_deposit: 70000,
    payment_frequency: 'monthly',
    status: 'active',
    terms: 'Residential executive lease with association rules.',
  },
  {
    property_slug: 'aci-eastwest-bank-bajada',
    tenant_name: 'EastWest Bank',
    lease_number: 'LSE-ACI-BAJADA-AB',
    start_date: '2023-06-01',
    end_date: '2028-05-31',
    rent_amount: 145000,
    security_deposit: 290000,
    payment_frequency: 'monthly',
    status: 'active',
    terms: 'Institutional commercial lease for ACI Buildings A and B.',
  },
  {
    property_slug: 'aci-landbank-san-pedro',
    tenant_name: 'Landbank of the Philippines',
    lease_number: 'LSE-LANDBANK-SAN-PEDRO',
    start_date: '2022-01-01',
    end_date: '2027-12-31',
    rent_amount: 95000,
    security_deposit: 190000,
    payment_frequency: 'monthly',
    status: 'active',
    terms: 'Long-term institutional tenant retention lease.',
  },
  {
    property_slug: 'amalgated-pryce-tower-1',
    tenant_name: 'Pryce Tower Resident',
    lease_number: 'LSE-PRYCE-TWR-1',
    start_date: '2025-03-01',
    end_date: '2026-02-28',
    rent_amount: 28000,
    security_deposit: 56000,
    payment_frequency: 'monthly',
    status: 'active',
    terms: 'Condominium residential lease subject to association rules.',
  },
  {
    property_slug: 'aci-la-fortuna-tagum',
    tenant_name: 'La Fortuna Tenant',
    lease_number: 'LSE-LA-FORTUNA-01',
    start_date: '2024-08-01',
    end_date: '2025-07-31',
    rent_amount: 22000,
    security_deposit: 44000,
    payment_frequency: 'monthly',
    status: 'renewed',
    terms: 'Regional residential lease in Tagum City.',
  },
];

export function catalogToDbLease(item, propertyId) {
  return {
    property_id: propertyId,
    tenant_name: item.tenant_name,
    lease_number: item.lease_number,
    start_date: item.start_date,
    end_date: item.end_date,
    rent_amount: item.rent_amount,
    security_deposit: item.security_deposit ?? 0,
    payment_frequency: item.payment_frequency ?? 'monthly',
    status: item.status ?? 'active',
    terms: item.terms ?? null,
  };
}
